#!/bin/sh

if [ "$1" != "eth0" ]; then
    exit 0
fi

# Configure login message to include local ip
LOCAL_IP=$(ifconfig eth0 | awk '/inet / {print $2}')
cat << EOF >/etc/issue 

\S
Kernel \r on an \m (${LOCAL_IP})

EOF

# Workaround for SystemD when you need the local ip
# This can then be included as a environment file
echo "LOCAL_IP=${LOCAL_IP}" > /etc/sysconfig/local-ip
