#!/bin/bash

set -eu

INFO="\033[1;32m"
WARN="\033[0;33m"
FATAL="\033[0;31m"
CLEAR='\033[0m'

info() {
    printf "${INFO}$1${CLEAR}\n"
}

warn() {
    printf "${WARN}WARN: $1${CLEAR}\n"
}

fatal() {
    printf "${FATAL}FATAL: $1${CLEAR}\n"
    exit 1
}

help() {
    echo "Usage: $0 [-h|--help] [-y|--yes] [--reboot] [-l|--list] [-d|--distro=<distro>] [-R|--repo=<repository>] [-i|--image=<image>] [-r|--registry=<registry>]"
}

# Load configuration
[ -f /etc/dock2box/config ] || fatal "Configuration file is missing: /etc/dock2box/config"
source /etc/dock2box/config

[ -z "${KERNEL:-}" ] && fatal "\$KERNEL is not set"
[ -z "${INITRD:-}" ] && fatal "\$KERNEL is not set"
[ -z "${DISTRO:-}" ] && fatal "\$DISTRO is not set"
[ -z "${IMAGE:-}" ] && fatal "\$IMAGE is not set"

[ -z "${REGISTRY:-}" ] && REGISTRY="registry.hub.docker.com"
[ -z "${REPO:-}" ] && REPO="dock2box"

# Get arguments
while [ -n "${1:-}" ]; do
    case "$1" in
        -d=*|--distro=*) DISTRO=${1#*=} ;;
        -R=*|--repo=*) REPO=${1#*=} ;;
        -i=*|--image=*) IMAGE=${1#*=} ;;
        -r=*|--registry=*) REGISTRY=${1#*=} ;;
        -l|--list) list="true" ;;
        -y|--yes) yes="true" ;;
        --reboot) reboot="true" ;;
        -h|--help)
            help
            exit 0
        ;;
        *)
            help
            fatal "Invalid argument: $1"
        ;;
    esac
    shift
done

# List images
if [ "${list:-false}" == "true" ]; then
    if [ "$REGISTRY" == "registry.hub.docker.com" ]; then
        curl -s -k https://$REGISTRY/v1/search?q=dock2box | jq -r '.results[].name'
    else
        curl -s -k https://$REGISTRY/v2/_catalog?n=10000 |  jq -r '.[][]' | grep ^dock2box\/
    fi
    exit 0
fi

# Verify arguments
echo "Distribution: $DISTRO"
echo "Image: $IMAGE"
echo "Registry: $REGISTRY"

if [ "${yes:-false}" == "false" ]; then
    read -p "Is this correct [y/n]? " -n 1 -r
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo
        exit 1
    fi
fi

# Get boot disk
boot=$( awk '/\/boot/ { print $1 }' /proc/mounts )
disk=$( echo $boot | sed 's/[0-9]$//' )
part=$( echo $boot | sed 's/^\/dev\/[a-z]*//' )

info "Download kernel"
curl --progress-bar -o /boot/dock2box-kernel $KERNEL

info "Download initrd"
curl --progress-bar -o /boot/dock2box-initrd $INITRD

info "Generate grub configuration"
grub2-mkconfig -o /boot/grub2/grub.cfg

info "Modify grub configuration"
[ -e /boot/grub2/grub.cfg ] || fatal "Grub configuration file doesn't exist: /boot/grub2/grub.cfg"
cat << EOF >>/boot/grub2/grub.cfg
menuentry 'Dock2Box Rebuild' {
  set root='hd0,$part'
  linux16 /dock2box-kernel ip=dhcp distro=$DISTRO image=$IMAGE registry=$REGISTRY install gpt
  initrd16 /dock2box-initrd
}
EOF

info "Set kernel as default"
grub2-set-default 'Dock2Box Rebuild'

info "Install grub"
grub2-install $disk

if [ "${reboot:-false}" == "true" ]; then
    warn "Will reboot in 3 sec."
    reboot -d 3
fi
